insert into state_image(id, state_id, algorithm_position, picture) values
(19, 24, 'ECG; ECG monitoring', '/images/states/HS_1-2.png'),
(20, 25, 'Specialized protocol ECG; EchoCG', '/images/states/HS_2-2.png'),
(21, 26, 'Main disease curing', '/images/states/HS_3-2.png'),
(22, 27, 'Exercise stress test', '/images/states/HS_4-2.png'),
(23, 28, 'EchoCG stress-testing, exercise test with Ng', '/images/states/HS_5-2.png'),
(24, 29, 'Psychodiagnostics', '/images/states/HS_6-2.png'),
(25, 30, 'Psychodiagnostics', '/images/states/HS_7-2.png'),
(26, 31, '8', '/images/states/HS_8-2.png'),
(27, 32, '9', '/images/states/HS_9-2.png'),
(28, 33, '10', '/images/states/HS_10-2.png'),
(29, 34, 'Beta blockers', '/images/states/HS_11-2.png'),
(30, 20, 'VA not registered', '/images/states/HSt_1-2.png'),
(31, 21, 'CAD; MR; CAD comprehensive treatment', '/images/states/HSt_2-2.png'),
(32, 22, 'Cured patient', '/images/states/HSt_3-2.png'),
(33, 23, 'CA is discussed with patient', '/images/states/HSt_4-2.png');
